### PR TITLE
declare the extension as parallel read safe

### LINKED ISSUE #170: sphinx warning about 'safe for parallel reading'
When I process a big complicated document, I see this warning: 

```
  sphinx-build -M html ./source ./build -N -j auto -q
WARNING: the sphinx_substitution_extensions extension does not declare if it is safe for parallel reading, assuming it isn't - please \
ask the extension author to check and make it explicit
WARNING: doing serial read
```
I tried to make a simple doc to reproduce the problem, but I don't get the message. Has anyone seen this warning and knows what triggers it and how to resolve it? I am using:
Sphinx-Substitution-Extensions==2020.7.4.1

### PR DESCRIPTION
**Pull request by rscohn2**
Resolves #170 

Declares the extension as [parallel read safe](https://www.sphinx-doc.org/en/master/extdev/index.html#extension-metadata)

### CODE REVIEW

**Comment by adamtheturtle** [comment]
Thank you @rscohn2 for the bug report and this contribution.

As per the comment on the issue, we can reproduce the bug by building a documentation set with > 5 documents and specifying `-j` in the Sphinx options to be `> 2`.

I would like for CI to fail without this change.

My suggestion of how that might be done:

* In the `sample/` directory, add a number of empty `.rst` files, so that we hit the 5 document threshold.
* In the `index.rst` file, include these new files in a `toctree`.
* Use the `:hidden:` setting on the `toctree` to avoid the output being modified.
* Add a comment by the `toctree` explaining that it is there, with the extra documents, to trigger the parallel read check.
* Create a `build-sample-parallel` target in the `Makefile` which is like `build-sample` but uses `-j 2`.
* Run `make build-sample-parallel` in `.github/workflows/ci.yml`

Are you happy to make these changes, or something else which triggers the issue in CI?

**Comment by rscohn2** [comment]
I added the test and verified that it fails without the change. I squashed and force-pushed to clean up the extra commits to correct lint errors. All the error checking is nice. I need to add it to my projects and get in the habit of doing it before committing.

**Comment by adamtheturtle** [comment]
Thanks @rscohn2 , and thanks for noticing the lint setup - it took a lot of work to get to this point (and there is still more to do!). I will merge this and then do a release.

**Comment by adamtheturtle** [comment]
@rscohn2 - the new release, `2020.9.30.0`, includes this change. Nice work!

**Comment by rscohn2** [comment]
Thanks for releasing quickly. I did not mention that I tried it on a 1500 page document, where it reduced processing time from 4.5 to 3.5 minutes.

**Pull request merged**
